scalar Date

type Transaction {
  id: ID,
  account: String,
  description: String,
  category: String,
  reference: String,
  currency: String,
  amount: Float,
  status: String,
  transactionDate: Date,
  createdAt: Date,
  updatedAt: Date
}

type Query {
  getAllTransactions(size: Int, skip: Int): [Transaction],
  getTransactionsByDateRange(startMonth: String, endMonth: String): [Transaction],
  getTransactionById(id: ID): Transaction
}